export { default as Dashboard } from './Dashboard'
export { default as Receitas } from './Receitas'
export { default as Despesas } from './Despesas'
export { default as Investimentos } from './Investimentos'
export { default as Perfil } from './Perfil'